[project]
name = "odp-el-toolchain"
version = "0.1.0"
dependencies = [
    "textX==4.2.2",
    "colorama==0.4.6"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ODP", "loader", "runtime"]